### ISSUE TITLE
add gem to gemfile, couldent start rails server

### ISSUE THREAD

**Issue by lyb124553153** [crashtech/torque-postgresql#39]
```
Traceback (most recent call last):
	112: from bin/rails:4:in `<main>'
	111: from bin/rails:4:in `require'
	110: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/railties-5.2.2.1/lib/rails/commands.rb:18:in `<top (required)>'
	109: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/railties-5.2.2.1/lib/rails/command.rb:46:in `invoke'
	108: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/railties-5.2.2.1/lib/rails/command/base.rb:65:in `perform'
	107: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	106: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	105: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	104: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/railties-5.2.2.1/lib/rails/commands/server/server_command.rb:142:in `perform'
	103: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/railties-5.2.2.1/lib/rails/commands/server/server_command.rb:142:in `tap'
	102: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/railties-5.2.2.1/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	101: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/railties-5.2.2.1/lib/rails/commands/server/server_command.rb:51:in `start'
	100: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/railties-5.2.2.1/lib/rails/commands/server/server_command.rb:89:in `log_to_stdout'
	 99: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/rack-2.0.7/lib/rack/server.rb:354:in `wrapped_app'
	 98: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/railties-5.2.2.1/lib/rails/commands/server/server_command.rb:27:in `app'
	 97: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/rack-2.0.7/lib/rack/server.rb:219:in `app'
	 96: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/rack-2.0.7/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	 95: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/rack-2.0.7/lib/rack/builder.rb:40:in `parse_file'
	 94: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/rack-2.0.7/lib/rack/builder.rb:49:in `new_from_string'
	 93: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/rack-2.0.7/lib/rack/builder.rb:49:in `eval'
	 92: from config.ru:in `<main>'
	 91: from config.ru:in `new'
	 90: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/rack-2.0.7/lib/rack/builder.rb:55:in `initialize'
	 89: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/rack-2.0.7/lib/rack/builder.rb:55:in `instance_eval'
	 88: from config.ru:3:in `block in <main>'
	 87: from config.ru:3:in `require_relative'
	 86: from /Users/liyongbo/workspace/pi-api/config/environment.rb:5:in `<top (required)>'
	 85: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/railties-5.2.2.1/lib/rails/application.rb:361:in `initialize!'
	 84: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/railties-5.2.2.1/lib/rails/initializable.rb:60:in `run_initializers'
	 83: from /Users/liyongbo/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
	 82: from /Users/liyongbo/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
	 81: from /Users/liyongbo/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
	 80: from /Users/liyongbo/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:347:in `call'
	 79: from /Users/liyongbo/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:347:in `each'
	 78: from /Users/liyongbo/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
	 77: from /Users/liyongbo/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
	 76: from /Users/liyongbo/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:415:in `call'
	 75: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/railties-5.2.2.1/lib/rails/initializable.rb:50:in `tsort_each_child'
	 74: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/railties-5.2.2.1/lib/rails/initializable.rb:50:in `each'
	 73: from /Users/liyongbo/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	 72: from /Users/liyongbo/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
	 71: from /Users/liyongbo/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	 70: from /Users/liyongbo/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	 69: from /Users/liyongbo/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
	 68: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/railties-5.2.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	 67: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/railties-5.2.2.1/lib/rails/initializable.rb:32:in `run'
	 66: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/railties-5.2.2.1/lib/rails/initializable.rb:32:in `instance_exec'
	 65: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/railties-5.2.2.1/lib/rails/engine.rb:613:in `block in <class:Engine>'
	 64: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/railties-5.2.2.1/lib/rails/engine.rb:613:in `each'
	 63: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/railties-5.2.2.1/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
	 62: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/railties-5.2.2.1/lib/rails/engine.rb:656:in `load_config_initializer'
	 61: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/notifications.rb:170:in `instrument'
	 60: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/railties-5.2.2.1/lib/rails/engine.rb:657:in `block in load_config_initializer'
	 59: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:285:in `load'
	 58: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	 57: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:285:in `block in load'
	 56: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:285:in `load'
	 55: from /Users/liyongbo/workspace/pi-api/config/initializers/form_core.rb:25:in `<top (required)>'
	 54: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:195:in `const_missing'
	 53: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:510:in `load_missing_constant'
	 52: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:356:in `require_or_load'
	 51: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:37:in `load_interlock'
	 50: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies/interlock.rb:13:in `loading'
	 49: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
	 48: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
	 47: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:37:in `block in load_interlock'
	 46: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:373:in `block in require_or_load'
	 45: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:475:in `load_file'
	 44: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:661:in `new_constants_in'
	 43: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:476:in `block in load_file'
	 42: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:476:in `load'
	 41: from /Users/liyongbo/workspace/pi-api/app/models/fields.rb:3:in `<top (required)>'
	 40: from /Users/liyongbo/workspace/pi-api/app/models/fields.rb:11:in `<module:Fields>'
	 39: from /Users/liyongbo/workspace/pi-api/app/models/fields.rb:11:in `each'
	 38: from /Users/liyongbo/workspace/pi-api/app/models/fields.rb:12:in `block in <module:Fields>'
	 37: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:246:in `require_dependency'
	 36: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:334:in `depend_on'
	 35: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:356:in `require_or_load'
	 34: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:37:in `load_interlock'
	 33: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies/interlock.rb:13:in `loading'
	 32: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
	 31: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
	 30: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:37:in `block in load_interlock'
	 29: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:373:in `block in require_or_load'
	 28: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:475:in `load_file'
	 27: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:661:in `new_constants_in'
	 26: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:476:in `block in load_file'
	 25: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:476:in `load'
	 24: from /Users/liyongbo/workspace/pi-api/app/models/fields/input_field.rb:3:in `<top (required)>'
	 23: from /Users/liyongbo/workspace/pi-api/app/models/fields/input_field.rb:4:in `<module:Fields>'
	 22: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:195:in `const_missing'
	 21: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:542:in `load_missing_constant'
	 20: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:195:in `const_missing'
	 19: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:510:in `load_missing_constant'
	 18: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:356:in `require_or_load'
	 17: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:37:in `load_interlock'
	 16: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies/interlock.rb:13:in `loading'
	 15: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
	 14: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
	 13: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:37:in `block in load_interlock'
	 12: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:373:in `block in require_or_load'
	 11: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:475:in `load_file'
	 10: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:661:in `new_constants_in'
	  9: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:476:in `block in load_file'
	  8: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:476:in `load'
	  7: from /Users/liyongbo/workspace/pi-api/app/models/optional_column.rb:1:in `<top (required)>'
	  6: from /Users/liyongbo/workspace/pi-api/app/models/optional_column.rb:5:in `<class:OptionalColumn>'
	  5: from /Users/liyongbo/workspace/pi-api/app/models/optional_column.rb:5:in `include'
	  4: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/concern.rb:122:in `append_features'
	  3: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/concern.rb:122:in `class_eval'
	  2: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/form_core-0.0.14/lib/form_core/concerns/models/field.rb:23:in `block in <module:Field>'
	  1: from /Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/torque-postgresql-1.0.1/lib/torque/postgresql/attributes.rb:27:in `method_missing'
/Users/liyongbo/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.2.1/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `accessibilities' for #<Class:0x00007feae1f62880> (NoMethodError)
```

**Comment by crashtech** [comment]
Which version you tried to use?

**Comment by lyb124553153** [comment]
> Which version did you try to use?
using rails5.2.2.1, torque-postgresql1.01
```
Using rake 12.3.3
Using concurrent-ruby 1.1.5
Using aasm 4.12.3
Using i18n 1.6.0
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 5.2.2.1
Using builder 3.2.3
Using erubi 1.8.0
Using mini_portile2 2.4.0
Using nokogiri 1.10.4
Using rails-dom-testing 2.0.3
Using crass 1.0.4
Using loofah 2.2.3
Using rails-html-sanitizer 1.2.0
Using actionview 5.2.2.1
Using rack 2.0.7
Using rack-test 1.1.0
Using actionpack 5.2.2.1
Using nio4r 2.4.0
Using websocket-extensions 0.1.4
Using websocket-driver 0.7.1
Using actioncable 5.2.2.1
Using globalid 0.4.2
Using activejob 5.2.2.1
Using mini_mime 1.0.2
Using mail 2.7.1
Using actionmailer 5.2.2.1
Using activemodel 5.2.2.1
Using arel 9.0.0
Using activerecord 5.2.2.1
Using active_record_union 1.3.0
Using mimemagic 0.3.3
Using marcel 0.3.3
Using activestorage 5.2.2.1
Using bundler 1.17.3
Using method_source 0.9.2
Using thor 0.20.3
Using railties 5.2.2.1
Using sprockets 3.7.2
Using sprockets-rails 3.2.1
Using rails 5.2.2.1
Using active_storage_validations 0.6.1
Using mime-types-data 3.2016.0521
Using mime-types 3.1
Using unf_ext 0.0.7.5
Using unf 0.1.4
Using domain_name 0.5.20170404
Using http-cookie 1.0.3
Using netrc 0.11.0
Using rest-client 2.0.2
Using qiniu 6.9.0
Using activestorage_qiniu 0.2.0
Using acts_as_list 0.9.11
Using public_suffix 3.0.3
Using addressable 2.6.0
Using aliyun-cloudpush 0.2.0
Using annotate 2.7.2
Using graphql 1.9.10
Using apollo_upload_server 2.0.0.beta.3
Using ast 2.4.0
Using auto_strip_attributes 2.4.0
Using awesome_print 1.8.0
Using msgpack 1.2.4
Using bootsnap 1.3.0
Using uniform_notifier 1.11.0
Using bullet 5.7.5
Using by_star 3.0.0
Using byebug 10.0.1
Using chinese_pinyin 1.0.1
Using with_advisory_lock 4.0.0
Using closure_tree 7.0.0
Using coderay 1.1.2
Using connection_pool 2.2.1
Using dalli 2.7.7
Using database_cleaner 1.6.2
Using opentracing 0.4.3
Using ddtrace 0.18.1
Using default_value_for 3.1.0
Using diff-lcs 1.3
Using dotenv 2.3.0
Using dotenv-rails 2.3.0
Using duck_record 0.0.24
Using et-orbi 1.1.0
Using fabrication 2.20.1
Using faker 1.8.7
Using multipart-post 2.0.0
Using faraday 0.14.0
Using ffi 1.10.0
Using form_core 0.0.14
Using formatador 0.2.5
Using fx 0.3.0 from https://github.com/mirahtech/fx.git (at feature/aggregates@e0de338)
Using geocoder 1.4.9
Using graphiql-rails 1.4.10
Using promise.rb 0.7.4
Using graphql-batch 0.4.1
Using graphql-guard 1.2.2
Using graphql-preload 2.1.0
Using graphql-schema_comparator 0.6.1
Using groupdate 4.0.0
Using rb-fsevent 0.10.3
Using rb-inotify 0.9.10
Using ruby_dep 1.5.0
Using listen 3.1.5
Using lumberjack 1.0.12
Using nenv 0.3.0
Using shellany 0.0.1
Using notiffany 0.1.1
Using pry 0.11.3
Using guard 2.14.2
Using guard-compat 1.2.1
Using rspec-support 3.7.1
Using rspec-core 3.7.1
Using rspec-expectations 3.7.0
Using rspec-mocks 3.7.0
Using rspec 3.7.0
Using guard-rspec 4.7.3
Using http-form_data 2.1.1
Using http_parser.rb 0.6.0
Using http 4.1.1
Using jaro_winkler 1.5.1
Using multi_json 1.13.1
Using jbuilder 2.7.0
Using json 2.1.0
Using json_web_token 0.3.5
Using jwt_claims 0.1.0
Using kaminari-core 1.1.1
Using kaminari-actionview 1.1.1
Using kaminari-activerecord 1.1.1
Using kaminari 1.1.1
Using lazy_priority_queue 0.1.1
Using ledermann-rails-settings 2.4.3
Using marginalia 1.6.0
Using measured 2.4.0
Using measured-rails 2.4.0
Using open4 1.3.4
Using mina 1.2.3
Using mina-multistage 1.0.3
Using mina-sidekiq 1.0.3
Using mini_magick 4.9.5
Using nanoid 0.2.0
Using null-logger 0.1.5
Using parallel 1.12.1
Using parallel_tests 2.27.0
Using paranoia 2.4.1
Using parser 2.5.3.0
Using pg 1.1.4
Using powerpack 0.1.2
Using pry-rails 0.3.6
Using public_activity 1.5.0
Using puma 3.11.3
Using pundit 1.1.0
Using rack-attack 6.0.0
Using rack-cors 1.0.2
Using rack-protection 2.0.1
Using rails-i18n 5.1.1
Using rainbow 3.0.0
Using ransack 2.1.1
Using redis 3.3.5
Using redlock 0.2.2
Using stream 0.5
Using rgl 0.5.3
Using rubyzip 1.2.2
Using roo 2.7.1
Using rspec-rails 3.7.2
Using ruby-progressbar 1.10.0
Using unicode-display_width 1.4.1
Using rubocop 0.62.0
Using ruby-ole 1.2.12.1
Using rufus-scheduler 3.4.2
Using scenic 1.4.1
Using second_level_cache 2.4.4
Using sentry-raven 2.7.2
Using shoulda-matchers 3.1.2 from https://github.com/thoughtbot/shoulda-matchers.git (at master@e35f083)
Using sidekiq 5.1.2
Using tilt 2.0.8
Using sidekiq-scheduler 2.2.1
Using simple_command 0.0.9
Using spreadsheet 1.1.7
Using spring 2.0.2
Using spring-watcher-listen 2.0.1
Using torque-postgresql 1.0.1
Using wechat 0.11.1
Using zstd-ruby 1.4.0.0
```

**Comment by crashtech** [comment]
@lyb124553153 Can you tell me if with the version on master is everything working? Lots of changes, fixes, and improvements have been pushed to master.

**Comment by lyb124553153** [comment]
> @lyb124553153 Can you tell me if with the version on master is everything working? Lots of changes, fixes, and improvements have been pushed to master.

still same issue,  look like had same confict with gem form_core
```
Using torque-postgresql 1.1.0 from https://github.com/crashtech/torque-postgresql.git (at master@a9ed3f2)
```

**Comment by jasl** [comment]
I think the problem is `torque` conflicts with AR's `enum`

**Comment by jasl** [comment]
It seems could be reproduce through:

- in table it has a `int` column `accessibility`
- in model `enum accessibility: {read_and_write: 0, readonly: 1, hidden: 2}`
- `model_instance.accessibility =  "read_and_write"` will raise `undefined method 'to_sym' for 0:Integer Did you mean? to_s`
- `Model.accessibilities` will raise `NoMethodError: undefined method 'accessibilities' for #<Class:0x00007fadc67911e0>`

**Comment by crashtech** [comment]
If that's the problem, you can do the following:
```ruby
# application.rb
Torque::PostgreSQL.configure do |c|
  c.enum.base_method = :pg_enum
end
```

**Comment by crashtech** [comment]
Try out this way and check if it works.

**Comment by lyb124553153** [comment]
> Try out this way and check if it works.

solved
