### ISSUE TITLE
Rails 7.1: data_source_exists? wrong number of arguments

### ISSUE THREAD

**Issue by yosiat** [crashtech/torque-postgresql#87]
Hi,

Working on upgrading my project to Rails 7.1.2 (together with `torque-postgresql` 3.3.0) and getting an error (with eager_load = true):

From: https://github.com/crashtech/torque-postgresql/blob/master/lib/torque/postgresql/schema_cache.rb#L101
Calling: https://github.com/rails/rails/blob/main/activerecord/lib/active_record/connection_adapters/schema_cache.rb#L41 which accepts extra-parameter of connection.

```
/Users/yosi/.rvm/gems/ruby-3.2.2/gems/activerecord-7.1.2/lib/active_record/connection_adapters/schema_cache.rb:316:in `data_source_exists?': wrong number of arguments (given 1, expected 2) (ArgumentError)
        from /Users/yosi/.rvm/gems/ruby-3.2.2/gems/torque-postgresql-3.3.0/lib/torque/postgresql/schema_cache.rb:102:in `add_model_name'
        from /Users/yosi/.rvm/gems/ruby-3.2.2/gems/torque-postgresql-3.3.0/lib/torque/postgresql/schema_cache/schema_reflection.rb:7:in `add_model_name'
        from /Users/yosi/.rvm/gems/ruby-3.2.2/gems/torque-postgresql-3.3.0/lib/torque/postgresql/schema_cache/bound_schema_reflection.rb:7:in `add_model_name'
        from /Users/yosi/.rvm/gems/ruby-3.2.2/gems/torque-postgresql-3.3.0/lib/torque/postgresql/inheritance.rb:93:in `reset_table_name'
        from /Users/yosi/.rvm/gems/ruby-3.2.2/gems/torque-postgresql-3.3.0/lib/torque/postgresql/base.rb:24:in `reset_table_name'
```

Made PR to fix this issue - https://github.com/crashtech/torque-postgresql/pull/88

**Comment by yosiat** [comment]
Thanks for the quick fix!
