### ISSUE TITLE
Rails 7.2: undefined method `inherited_tables' for nil

### ISSUE THREAD

**Issue by yosiat** [crashtech/torque-postgresql#94]
Hi!

Trying to upgrade to Rails 7.2 (with latest version of torque-postgresql), and looks like this gem isn't ready for it:

```
/Users/yosi/.rvm/gems/ruby-3.3.1/bundler/gems/torque-postgresql-8caf4d0aa88c/lib/torque/postgresql/schema_cache.rb:132:in `reload_inheritance_data!': undefined method `inherited_tables' for nil (NoMethodError)

          @inheritance_dependencies = connection.inherited_tables
                                                ^^^^^^^^^^^^^^^^^
        from /Users/yosi/.rvm/gems/ruby-3.3.1/bundler/gems/torque-postgresql-8caf4d0aa88c/lib/torque/postgresql/schema_cache.rb:109:in `dependencies'
        from /Users/yosi/.rvm/gems/ruby-3.3.1/bundler/gems/torque-postgresql-8caf4d0aa88c/lib/torque/postgresql/schema_cache/schema_reflection.rb:11:in `dependencies'
        from /Users/yosi/.rvm/gems/ruby-3.3.1/bundler/gems/torque-postgresql-8caf4d0aa88c/lib/torque/postgresql/schema_cache/bound_schema_reflection.rb:11:in `dependencies'
        from /Users/yosi/.rvm/gems/ruby-3.3.1/bundler/gems/torque-postgresql-8caf4d0aa88c/lib/torque/postgresql/inheritance.rb:60:in `physically_inherited?'
        from /Users/yosi/.rvm/gems/ruby-3.3.1/bundler/gems/torque-postgresql-8caf4d0aa88c/lib/torque/postgresql/inheritance.rb:114:in `base_class'
        from /Users/yosi/.rvm/gems/ruby-3.3.1/gems/activerecord-7.2.0/lib/active_record/inheritance.rb:120:in `base_class?'
```

Reproducer:
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "7.2"
  gem "pg"
  gem "torque-postgresql", git: "https://github.com/crashtech/torque-postgresql", branch: "master"
end

require "active_record"
require "logger"
require "torque-postgresql"

ActiveRecord::Base.establish_connection(
  adapter: "postgresql",
  database: "test",
  encoding: "unicode",
  host: "localhost",
  port: "5432",
  password: "12345",
  username: "test")

ActiveRecord::Schema.define do
  create_table :comments, force: true do |t|
    t.string :body
  end
end

class Comment < ActiveRecord::Base
end

Comment.create!
```

**Comment by yosiat** [comment]
I see other issues with Rails 7.2 and Torque.

@crashtech if you want I will list them in this issue OR will open different issues.

**Comment by crashtech** [comment]
Hey @yosiat. You can list them here! Depending on the size, I will check how quickly I can address them.

**Comment by yosiat** [comment]
`distinct_on` isn't working:
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "7.2"
  gem "pg"
  gem "torque-postgresql", git: "https://github.com/crashtech/torque-postgresql", branch: "master"
end

require "active_record"
require "logger"
require "torque-postgresql"

# Patching the inehritance module to avoid (earlier reported) error of `inherited_tables`
module Torque::PostgreSQL::Inheritance::ClassMethods
  def physically_inherited?
    false
  end

  def physically_inheritances?
    false
  end
end

ActiveRecord::Base.establish_connection(
  adapter: "postgresql",
  database: "test",
  encoding: "unicode",
  host: "localhost",
  port: "5432",
  password: "12345",
  username: "test"
)

ActiveRecord::Schema.define do
  create_table :comments, force: true do |t|
    t.string :body
  end
end

class Comment < ActiveRecord::Base
end

Comment.all.distinct_on(:body).to_a
```

Error:
```
/Users/yosi/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.0/lib/active_record/relation/delegation.rb:122:in `method_missing': undefined method `assert_mutability!' for an instance of ActiveRecord::Relation (NoMethodError)
Did you mean?  assert_modifiable!
        from /Users/yosi/.rvm/gems/ruby-3.3.4/bundler/gems/torque-postgresql-cdb8a327cc59/lib/torque/postgresql/relation.rb:105:in `set_value'
        from /Users/yosi/.rvm/gems/ruby-3.3.4/bundler/gems/torque-postgresql-cdb8a327cc59/lib/torque/postgresql/relation/distinct_on.rb:11:in `distinct_on_values='
        from /Users/yosi/.rvm/gems/ruby-3.3.4/bundler/gems/torque-postgresql-cdb8a327cc59/lib/torque/postgresql/relation/distinct_on.rb:30:in `distinct_on!'
        from /Users/yosi/.rvm/gems/ruby-3.3.4/bundler/gems/torque-postgresql-cdb8a327cc59/lib/torque/postgresql/relation/distinct_on.rb:25:in `distinct_on'
```

I saw another issue which I can't reproduce yet, so will report it once I have reproducer script.

**Comment by yosiat** [comment]
This is the extra bug that I can't create a reproduced script. It happens only when I boot my app in production environment.

```
Did you mean? with_options
from /project/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.0/lib/active_record/connection_adapters/schema_cache.rb:313:in `data_source_exists?'
from /project/vendor/bundle/ruby/3.3.0/gems/torque-postgresql-3.3.3/lib/torque/postgresql/schema_cache.rb:102:in `add_model_name'
from /project/vendor/bundle/ruby/3.3.0/gems/torque-postgresql-3.3.3/lib/torque/postgresql/schema_cache/schema_reflection.rb:7:in `add_model_name'
from /project/vendor/bundle/ruby/3.3.0/gems/torque-postgresql-3.3.3/lib/torque/postgresql/schema_cache/bound_schema_reflection.rb:7:in `add_model_name'
from /project/vendor/bundle/ruby/3.3.0/gems/torque-postgresql-3.3.3/lib/torque/postgresql/inheritance.rb:93:in `reset_table_name'
from /project/vendor/bundle/ruby/3.3.0/gems/torque-postgresql-3.3.3/lib/torque/postgresql/base.rb:24:in `reset_table_name'
from /project/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.0/lib/active_record/model_schema.rb:261:in `table_name'
from /project/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.0/lib/active_record/model_schema.rb:295:in `reset_table_name'
from /project/vendor/bundle/ruby/3.3.0/gems/torque-postgresql-3.3.3/lib/torque/postgresql/inheritance.rb:89:in `reset_table_name'
from /project/vendor/bundle/ruby/3.3.0/gems/torque-postgresql-3.3.3/lib/torque/postgresql/base.rb:24:in `reset_table_name'
from /project/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.0/lib/active_record/model_schema.rb:261:in `table_name'
from /project/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.0/lib/active_record/model_schema.rb:297:in `reset_table_name'
from /project/vendor/bundle/ruby/3.3.0/gems/torque-postgresql-3.3.3/lib/torque/postgresql/inheritance.rb:89:in `reset_table_name'
from /project/vendor/bundle/ruby/3.3.0/gems/torque-postgresql-3.3.3/lib/torque/postgresql/base.rb:24:in `reset_table_name'
from /project/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.0/lib/active_record/model_schema.rb:261:in `table_name'
from /project/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.0/lib/active_record/model_schema.rb:588:in `load_schema!'
from /project/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.0/lib/active_record/counter_cache.rb:187:in `load_schema!'
from /project/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.0/lib/active_record/encryption/encryptable_record.rb:127:in `load_schema!'
from /project/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.0/lib/active_record/model_schema.rb:539:in `block in load_schema'
from /project/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.0/lib/active_record/model_schema.rb:536:in `synchronize'
from /project/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.0/lib/active_record/model_schema.rb:536:in `load_schema'
from /project/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.0/lib/active_record/model_schema.rb:429:in `columns_hash'
from /project/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.0/lib/active_record/attributes.rb:243:in `block in _default_attributes'
from /project/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:413:in `with_connection'
from /project/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.0/lib/active_record/connection_handling.rb:296:in `with_connection'
from /project/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.0/lib/active_record/attributes.rb:242:in `_default_attributes'
from /project/vendor/bundle/ruby/3.3.0/gems/activemodel-7.2.0/lib/active_model/attribute_registration.rb:38:in `attribute_types'
from /project/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.0/lib/active_record/attribute_methods.rb:260:in `_has_attribute?'
from /project/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.0/lib/active_record/inheritance.rb:61:in `new'
```

**Comment by tomasc** [comment]
Also noticed:

```
NoMethodError: undefined method `assert_mutability!' for an instance of ActiveRecord::Relation (NoMethodError)
Did you mean?  assert_modifiable!
```

Coming probably from https://github.com/crashtech/torque-postgresql/blob/cdb8a327cc59c621e4106a78d34ac427bee3fe8e/lib/torque/postgresql/relation.rb#L105

**Comment by crashtech** [comment]
@tomasc Rails 7.2 is now supported by version `3.4.0`

**Comment by tomasc** [comment]
thank you @crashtech , much appreciated!
